### ISSUE TITLE
Aimed Shot not working

### ISSUE THREAD

**Issue by karyzan** [Nevcairiel/Quartz#3]
Is it possible to fix Aimed Shot for Quartz? That would be amazing!

**Comment by Nevcairiel** [comment]
I don't have a Hunter on Classic, and leveling is zero fun just to fix an addon, sorry.

**Comment by hallabro** [comment]
@karyzan could you please try the fix in #7?

**Comment by Nevcairiel** [comment]
Aimed Shot should now work as of ae03eb5807161ade2bf672aa484fd109c1c7de19, as LibClassicCasterino provides data for it

**Comment by hallabro** [comment]
@Nevcairiel looking good, thanks!
