### ISSUE TITLE
Error at login in TBC

### ISSUE THREAD

**Issue by Daeveren** [Nevcairiel/Quartz#35]
`Message: Interface\AddOns\Quartz\modules\Player.lua:230: attempt to call global 'GetActiveSpecGroup' (a nil value)
Time: Wed Jun 23 13:53:01 2021
Count: 1
Stack: Interface\AddOns\Quartz\modules\Player.lua:230: attempt to call global 'GetActiveSpecGroup' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Quartz\modules\Player.lua"]:230: in function <Interface\AddOns\Quartz\modules\Player.lua:229>
[string "@Interface\AddOns\Quartz\modules\Player.lua"]:237: in function `UpdateChannelingTicks'
[string "@Interface\AddOns\Quartz\modules\Player.lua"]:105: in function <Interface\AddOns\Quartz\modules\Player.lua:97>
[string "=[C]"]: ?
[string "@Interface\AddOns\Accountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ccountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Accountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Accountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Accountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ccountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>`

**Comment by lclancey** [comment]
https://github.com/Nevcairiel/Quartz/pull/34#issue-662202038

**Comment by lclancey** [comment]
Still not fixed in the newest commit...

**Comment by raethkcj** [comment]
@Nevcairiel any thoughts on either of the PRs intended to fix this? #34 #37
