### ISSUE TITLE
Not seeing dots/debuffs for target and cooldowns in WoW Classic

### ISSUE THREAD

**Issue by robhaswell** [Nevcairiel/Quartz#4]
Retail Quartz has super-useful debuff timers for my target and shows my own cooldown on abilities, but I haven't seen these in Classic yet.

Is this a missing feature or a problem with my installation?

**Comment by tstirrat** [comment]
Same here, it's not a problem with your installation. I think it's not implemented in classic yet.

**Comment by Nevcairiel** [comment]
Should be resolved as of 2ca10a55df6ac9d7ab358e0e10ada6d9afe841de

**Comment by incrediboy111** [comment]
I'm having a related issue - I can see buffs/debuffs when I target myself, but not with any other target. This includes buffs and debuffs that I put on them. Do I have something set up wrong?
