### ISSUE TITLE
BackdropTemplate changes are now implemented in 1.14

### ISSUE THREAD

**Issue by raethkcj** [Nevcairiel/Quartz#40]
The changes to SetBackdrop that require inheriting from BackdropTemplate are now in 1.14 (Classic Era and Season of Mastery).

**Comment by Jazzman1976** [comment]
Will there be an official 1.14.1 fix for Quartz by the original author?
Quartz is one of the most used AddOns, pls don't forget all those who love classic era and som.
Would love to see a fix, soon. All these "community fixed versions" don't work :-(
