### ISSUE TITLE
WoW SoM (V1.4.3) - Enemy castbar not working

### ISSUE THREAD

**Issue by maximus210793** [Nevcairiel/Quartz#45]
Can you update for WoW Classic Season of mastery version 1.4.3?
Since castbars are still not working :(
Would be awesome, thanks a lot!

**Comment by maximus210793** [comment]
Can you update for WoW Classic Season of mastery version 1.4.3?
Since castbars are still not working :(
Would be awesome, thanks a lot!

**Comment by Nevcairiel** [comment]
Blizzard does not provide enemy castbar information on Classic, as its historically accurate this way.

**Comment by maximus210793** [comment]
The nameplate addon plater does show exact timers, any my earlier quartz versions also did in WoW SoM. Just after the latest update to V1.4.3 they disappear.

**Comment by maximus210793** [comment]
Could you fix it?
