### ISSUE TITLE
Wrath Classic PTR - Channeling ticks don't show

### ISSUE THREAD

**Issue by flemwad** [Nevcairiel/Quartz#51]
I'm unable to see channeling ticks with version 3.6.11 on the Public Test Realm (Wrath Classic). But I can see them on the TBC classic version just fine. I'm on a warlock using drain soul.

Feel free to close if you're working on it or already aware just figured I'd let you know if not.

**Comment by Nevcairiel** [comment]
Channeling ticks need to be defined for each spell directly, and with many spell changes on Wrath, the information is just not available right now.

**Comment by Nevcairiel** [comment]
I've copied over the channeling spells from BCC (those that still apply, anyway). Additional information will need to be added later.
