### ISSUE TITLE
[WoTLK] Invalid icon for spell Conjure Mana Gem (sapphire)

### ISSUE THREAD

**Issue by Iowerth** [Nevcairiel/Quartz#58]
Hi. Version 3.7.0 for WoTLK.
When casting Conjure Mana Gem then showing Mana Emerald icon (134134) instead of Mana Sapphire icon (134132).

**Comment by Nevcairiel** [comment]
The icons are provided by the game. Quartz just shows them.

**Comment by Iowerth** [comment]
Game shows correct icon on panels. As do ElvUI, WeakAuras and other addons. Just need to specify correct icon ID in addon's code.

**Comment by Nevcairiel** [comment]
Quartz does not specify any icons. The game provides them.

**Comment by Iowerth** [comment]
Ok, may you please hardcode it? Like in other addons.

**Comment by Nevcairiel** [comment]
No. Sorry.
