### ISSUE TITLE
Classic target cast bars

### ISSUE THREAD

**Issue by nathanmarks** [Nevcairiel/Quartz#6]
@Nevcairiel 

I've got target cast bars working in classic with some local modifications to the addon -- would you be interested in officially supporting this in the addon if I throw up a PR?

**Comment by oskari** [comment]
You could just do the PR and let the community to adopt the changes even if the original author isn't willing to add the changes.

**Comment by GPopov** [comment]
I have added a PR that uses LibClassicCasterino to enable the Target cast bars in classic.

**Comment by Nevcairiel** [comment]
This was added in ae03eb5807161ade2bf672aa484fd109c1c7de19
