### ISSUE TITLE
[Cata] - C_TradeSkillUI issue in Tradeskill.lua

### ISSUE THREAD

**Issue by lordblackadder** [Nevcairiel/Quartz#85]
It seems Blizzard introduced C_TradeSkillUI with Cata build 4.4.0.54670, but only partially
![image](https://github.com/Nevcairiel/Quartz/assets/12127284/ac3046f4-4245-4c7f-a710-7fba21c50f70)

This causes Tradeskill.lua to error out in a check upon login because it finds C_TradeSkillUI, but not the function it's trying to hook

On v3.7.9:
```
Message: Interface/AddOns/Quartz/modules/Tradeskill.lua line 101:
Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
```

**Comment by Iowerth** [comment]
@lordblackadder for temporarily fix try this:
1. Open file` \Interface\AddOns\Quartz\modules\Tradeskill.lua`
2. Go to line 101: `self:SecureHook(C_TradeSkillUI, "CraftRecipe", "DoTradeSkillClassic")`
3. Replace it to: `self:SecureHook("DoTradeSkill", "DoTradeSkillClassic")`
4. Reload UI if all above were made while game running.
