### ISSUE TITLE
Samwise Icon Fails to Hide & Displays on all Professions

### ISSUE THREAD

**Issue by RonPaul2012** [Nevcairiel/Quartz#9]
Samwise Icon is still shown for some bars - particularly trade skill related

This is the main reason I have disabled Quartz. I do not understand why the Samwise icon is displaying for ANY  Profession or CRAFTING action. I've gone back to Dominos default cast bar because it properly shows atlast the profession spellid icon per cast. I cannot stand seeing a blank box/samewise icon for every bag I tailor.

 
If you can fix this, and properly show trade skill/other icons, I will be very pleased as this is the best cast bar addon - but the fact Samwise icon is showing up for 100% of my non-spells is just obnoxious

**Comment by Nevcairiel** [comment]
The Samwise Icon (or no Icon) shows if the spell you are currently casting does not have an icon of its own. You can thank Blizzard for not assigning Icons to their spells.

**Comment by RonPaul2012** [comment]
With that in-mind, can you look at Dominos Castbar for example, and see how they are pulling Icon IDs?

Atleast with Dominos, I'm able to see a half-relevant icon. 

Smelting/Mining/Enchanting/Cooking/Tailoring/Any crafting profession shows the SAMWISE Icon even when I have "Hide Samwise Icon" within Quartz. The issue is that SAMWISE is still appearing, even with the option disabled; on top of that, as you said, if the ability does not have a specific Blizz Icon ID, it appears as completely blank OR the Samwise icon.

A simple fix for this would be to implement something similar to Dominos; a "placeholder" icon instead of it showing an empty gray box or an annoying big head.

**Comment by Nevcairiel** [comment]
I actually did something already, replacing it with a cogwheel icon because the blank box looked bad, and also doign that for professions

You can grab a version with that here (for classic):
https://www.wowace.com/projects/quartz/files/2804925

**Comment by RonPaul2012** [comment]
Awesome. If possible, we could take it a step further and hard core the profession icons to each spell ID.

Example:
Blacksmithing
Name: trade_blacksmithing
Skill ID: 164
Icon ID: 136241

I'm willing to compile all relevant profession skills in the above format if you'd be open to adding them into Quartz.

**Comment by Nevcairiel** [comment]
I really don't want a list of every possible crafting recipe, but maybe there is a way to make that smarter. I'll think about it.

**Comment by RonPaul2012** [comment]
True. I forgot it's current logic would require it to be pulled for every spell within those specific skills.

But, possibly, code some logic that assumes the default profession icon (like above) for all casts within that profession. I'm not sure how this could easily be achieved; but each profession has a usable base Skill and Icon ID available which match the icons shown in the spell book.

Thanks for the update. I'll download and test the version you linked me.

**Comment by Nevcairiel** [comment]
I found a way to use the icon of the crafting recipe pretty easily, that should make it perfect.

There is a new version here:
https://www.wowace.com/projects/quartz/files/2816630
