### ISSUE TITLE
11.0 LUA error - CLI not working

### ISSUE THREAD

**Issue by Andf** [Nevcairiel/Quartz#90]
Hiya!

When using /quartz command nothing happens and LUA errors are triggered (pasted below). Addon is working and I can change configuration using Blizzard menu.

4x Quartz/Config.lua:197: attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@Quartz/Config.lua"]:197: in function `?'
[string "@Bartender4/libs/AceConsole-3.0-7/AceConsole-3.0.lua"]:90: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5440: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5386>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5092: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5091>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5128: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
self = <table> {
 unlock = true
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 CastBarTemplate = <table> {
 }
 name = "Quartz3"
 orderedModules = <table> {
 }
 Util = <table> {
 }
 unlock_dialog = Quartz3UnlockDialog {
 }
 optFrames = <table> {
 }
 baseName = "Quartz"
 db = <table> {
 }
 defaultModuleState = true
 enabledState = true
}
input = ""
(*temporary) = nil
(*temporary) = Frame {
 obj = <table> {
 }
 parent = "Quartz 3"
 name = 84
}
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)"
Quartz3 = <table> {
 unlock = true
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 CastBarTemplate = <table> {
 }
 name = "Quartz3"
 orderedModules = <table> {
 }
 Util = <table> {
 }
 unlock_dialog = Quartz3UnlockDialog {
 }
 optFrames = <table> {
 }
 baseName = "Quartz"
 db = <table> {
 }
 defaultModuleState = true
 enabledState = true
}

**Comment by Nevcairiel** [comment]
This has been fixed

**Comment by Andf** [comment]
> This has been fixed

Many thanks for the swift fix, jolly good job!
